name: Deploy to EC2 and Docker Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and build Docker image
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'ENDSSH'
            cd ~/test-folder
            ls -la
          ENDSSH
          
      - name: Copy code to EC2
        run: scp -o StrictHostKeyChecking=no -r . ec2-user@${{ secrets.EC2_HOST }}:~/test-folder

