name: Deploy to EC2 and Docker Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0
      - name: Checkout code
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no  private_key ec2-user@${{ secrets.EC2_HOST }} '
            cd ~/test-folder
            ls -la
  
      - name: Copy code to EC2
        run: scp -o StrictHostKeyChecking=no private_key -r . ec2-user@${{ secrets.EC2_HOST }}:~/test-folder

